#!/usr/bin/env python3
"""
build_words.py — assemble TUMBLER's static word data.

Sources (all local/offline-friendly once fetched):
  * /usr/share/dict/american-english + british-english  -> validation set
    (every reasonable guess a player types should be accepted)
  * google-10000-english-no-swears.txt                  -> answer pool
    (only common words become vault combinations, so secrets are always fair)

Output:
  data/words.json   canonical data (human-inspectable, requested format)
  js/words.js       same data as window.TUMBLER_WORDS so the page works
                    from file:// AND GitHub Pages with zero fetch/CORS issues

Run:  python3 tools/build_words.py
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LENGTHS = (4, 5, 6)

DICTS = [
    "/usr/share/dict/american-english",
    "/usr/share/dict/british-english",
]
COMMON = os.environ.get("COMMON_WORDS", "/tmp/google10k.txt")

# A small safety net on top of the "no-swears" common list, applied to ANSWERS
# only (the words shown as secrets). The big validation set may still contain
# these as accepted guesses, which is fine.
BLOCK = {
    "shit", "fuck", "cunt", "damn", "slut", "tits", "porn", "cock",
    "anus", "arse", "crap", "dick", "piss", "twat", "wank", "rape",
    "nazi", "kill", "dead", "died", "dies", "guns",
}

WORD_RE = {n: re.compile(r"^[a-z]{%d}$" % n) for n in LENGTHS}


def read_lines_raw(path):
    try:
        with open(path, encoding="utf-8", errors="ignore") as fh:
            return [ln.strip() for ln in fh if ln.strip()]
    except FileNotFoundError:
        return []


def read_lines(path):
    return [w.lower() for w in read_lines_raw(path)]


def build():
    valid = {n: set() for n in LENGTHS}
    propers = set()  # lowercased forms of capitalized dict entries (names, places, acronyms)
    for d in DICTS:
        for raw in read_lines_raw(d):
            if raw[:1].isupper():
                propers.add(raw.lower())
            w = raw.lower()
            n = len(w)
            if n in WORD_RE and WORD_RE[n].match(w):
                valid[n].add(w)

    common = read_lines(COMMON)
    if not common:
        sys.exit("ERROR: common word list not found at %s — "
                 "fetch google-10000-english-no-swears.txt first." % COMMON)

    answers = {n: [] for n in LENGTHS}
    seen = {n: set() for n in LENGTHS}
    for w in common:                       # preserves frequency order (most common first)
        n = len(w)
        if n not in WORD_RE or not WORD_RE[n].match(w):
            continue
        if w in valid[n] and w not in BLOCK and w not in propers:  # no proper nouns as secrets
            if w not in seen[n]:
                seen[n].add(w)
                answers[n].append(w)

    out = {}
    for n in LENGTHS:
        # every answer must also be an accepted guess
        valid[n].update(answers[n])
        out[str(n)] = {
            "answers": answers[n],                 # common -> fair secrets
            "valid": sorted(valid[n]),             # broad -> accepts real words
        }

    os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
    os.makedirs(os.path.join(ROOT, "js"), exist_ok=True)

    json_path = os.path.join(ROOT, "data", "words.json")
    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(out, fh, separators=(",", ":"), ensure_ascii=False)

    js_path = os.path.join(ROOT, "js", "words.js")
    with open(js_path, "w", encoding="utf-8") as fh:
        fh.write("/* Auto-generated by tools/build_words.py — do not edit by hand. */\n")
        fh.write("window.TUMBLER_WORDS=")
        json.dump(out, fh, separators=(",", ":"), ensure_ascii=False)
        fh.write(";\n")

    total_valid = sum(len(out[str(n)]["valid"]) for n in LENGTHS)
    total_ans = sum(len(out[str(n)]["answers"]) for n in LENGTHS)
    for n in LENGTHS:
        print("  len %d  answers %-5d  valid %-6d"
              % (n, len(out[str(n)]["answers"]), len(out[str(n)]["valid"])))
    print("  TOTAL  answers %d  valid %d" % (total_ans, total_valid))
    print("  wrote %s (%d KB)" % (json_path, os.path.getsize(json_path) // 1024))
    print("  wrote %s (%d KB)" % (js_path, os.path.getsize(js_path) // 1024))


if __name__ == "__main__":
    build()
